### ISSUE TITLE
How to load 3d bounding box labels?

### ISSUE THREAD

**Issue by tjtanaa** [leddartech/pioneer.das.api#4]
Could you provide examples as to how to load the label?

I would like to load **ouster64** point cloud data with **bounding box labels** instead of just **pixell_bfc_echo** with **bounding box labels**.

from the examples in https://github.com/leddartech/object_detection_pixell.git 
I have changed the  configuration file

```
DATASET:
  TRAIN_SET: '' # Path to the train set
  TEST_SET: '' # Path to the test set
  LIDAR: &lidar 'ouster64_bfc_xyzit'
  LABEL: &label 'pixell_bfc_box3d-deepen'
```

However, there is zero sample returned.
